version: "3"

services:
  database:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./app/.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
  web:
    build: .
    restart: always
    # command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database